// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/manga-landing/MangaLanding.tsx": () => import("../components/mockups/manga-landing/MangaLanding.tsx")
};
